# Generated by Django 3.2.4 on 2021-06-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='имя пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Complited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_number', models.IntegerField(verbose_name='Номер опроса')),
                ('question_number', models.IntegerField(verbose_name='Номер вопроса')),
                ('answer', models.TextField(verbose_name='Ответ пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.user')),
            ],
        ),
    ]
